// This file was automatically generated by bifcl from /home/ubuntu/bro/src/logging/writers/ascii/ascii.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_logging_writers_ascii_ascii_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_logging_writers_ascii_ascii_bif
#define _home_ubuntu_bro_my_build_dir_src_logging_writers_ascii_ascii_bif
#include "bro-bif.h"
#endif
#endif

namespace BifConst { namespace LogAscii {  extern int output_to_stdout;  }  }
namespace BifConst { namespace LogAscii {  extern int include_meta;  }  }
namespace BifConst { namespace LogAscii {  extern StringVal* meta_prefix;  }  }
namespace BifConst { namespace LogAscii {  extern StringVal* separator;  }  }
namespace BifConst { namespace LogAscii {  extern StringVal* set_separator;  }  }
namespace BifConst { namespace LogAscii {  extern StringVal* empty_field;  }  }
namespace BifConst { namespace LogAscii {  extern StringVal* unset_field;  }  }
namespace BifConst { namespace LogAscii {  extern int use_json;  }  }
namespace BifConst { namespace LogAscii {  extern Val* json_timestamps;  }  }
namespace BifConst { namespace LogAscii {  extern bro_uint_t gzip_level;  }  }

#endif
