// This file was automatically generated by bifcl from /home/ubuntu/bro/src/logging/writers/ascii/ascii.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "ascii.bif.h"

namespace plugin { namespace Bro_AsciiWriter {

void __bif_ascii_init(plugin::Plugin* plugin)
	{
	BifConst::LogAscii::output_to_stdout = internal_const_val("LogAscii::output_to_stdout")->AsBool();
	plugin->AddBifItem("LogAscii::output_to_stdout", plugin::BifItem::CONSTANT);
	BifConst::LogAscii::include_meta = internal_const_val("LogAscii::include_meta")->AsBool();
	plugin->AddBifItem("LogAscii::include_meta", plugin::BifItem::CONSTANT);
	BifConst::LogAscii::meta_prefix = internal_const_val("LogAscii::meta_prefix")->AsStringVal();
	plugin->AddBifItem("LogAscii::meta_prefix", plugin::BifItem::CONSTANT);
	BifConst::LogAscii::separator = internal_const_val("LogAscii::separator")->AsStringVal();
	plugin->AddBifItem("LogAscii::separator", plugin::BifItem::CONSTANT);
	BifConst::LogAscii::set_separator = internal_const_val("LogAscii::set_separator")->AsStringVal();
	plugin->AddBifItem("LogAscii::set_separator", plugin::BifItem::CONSTANT);
	BifConst::LogAscii::empty_field = internal_const_val("LogAscii::empty_field")->AsStringVal();
	plugin->AddBifItem("LogAscii::empty_field", plugin::BifItem::CONSTANT);
	BifConst::LogAscii::unset_field = internal_const_val("LogAscii::unset_field")->AsStringVal();
	plugin->AddBifItem("LogAscii::unset_field", plugin::BifItem::CONSTANT);
	BifConst::LogAscii::use_json = internal_const_val("LogAscii::use_json")->AsBool();
	plugin->AddBifItem("LogAscii::use_json", plugin::BifItem::CONSTANT);
	BifConst::LogAscii::json_timestamps = internal_const_val("LogAscii::json_timestamps");
	plugin->AddBifItem("LogAscii::json_timestamps", plugin::BifItem::CONSTANT);
	BifConst::LogAscii::gzip_level = internal_const_val("LogAscii::gzip_level")->AsCount();
	plugin->AddBifItem("LogAscii::gzip_level", plugin::BifItem::CONSTANT);

	}
} }


