// This file was automatically generated by bifcl from /home/ubuntu/bro/src/logging/writers/ascii/ascii.bif (plugin mode).


#include "ascii.bif.h"

namespace BifConst { namespace LogAscii {  int output_to_stdout;  }  }
namespace BifConst { namespace LogAscii {  int include_meta;  }  }
namespace BifConst { namespace LogAscii {  StringVal* meta_prefix;  }  }
namespace BifConst { namespace LogAscii {  StringVal* separator;  }  }
namespace BifConst { namespace LogAscii {  StringVal* set_separator;  }  }
namespace BifConst { namespace LogAscii {  StringVal* empty_field;  }  }
namespace BifConst { namespace LogAscii {  StringVal* unset_field;  }  }
namespace BifConst { namespace LogAscii {  int use_json;  }  }
namespace BifConst { namespace LogAscii {  Val* json_timestamps;  }  }
namespace BifConst { namespace LogAscii {  bro_uint_t gzip_level;  }  }
