# Install script for directory: /home/ubuntu/bro/src/analyzer/protocol

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "RelWithDebInfo")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/arp/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/ayiya/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/backdoor/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/bittorrent/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/conn-size/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/dce-rpc/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/dhcp/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/dnp3/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/dns/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/file/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/finger/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/ftp/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/gnutella/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/gssapi/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/gtpv1/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/http/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/icmp/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/ident/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/imap/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/interconn/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/irc/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/krb/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/login/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/mime/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/modbus/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/mysql/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/ncp/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/netbios/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/ntlm/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/ntp/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/pia/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/pop3/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/radius/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/rdp/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/rfb/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/rpc/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/sip/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/snmp/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/smb/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/smtp/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/socks/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/ssh/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/ssl/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/stepping-stone/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/syslog/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/tcp/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/teredo/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/udp/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/xmpp/cmake_install.cmake")
  include("/home/ubuntu/bro/my_build_dir/src/analyzer/protocol/zip/cmake_install.cmake")

endif()

