// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/tcp/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_TCP {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_TCP_events("Bro::TCP", __bif_events_init);
} }
