// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/tcp/functions.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_analyzer_protocol_tcp_functions_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_tcp_functions_bif
#define _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_tcp_functions_bif
#include "bro-bif.h"
#endif
#endif

namespace BifFunc { extern Val* bro_get_orig_seq(Frame* frame, val_list*); } 
namespace BifFunc { extern Val* bro_get_resp_seq(Frame* frame, val_list*); } 
namespace BifFunc { extern Val* bro_set_contents_file(Frame* frame, val_list*); } 
namespace BifFunc { extern Val* bro_get_contents_file(Frame* frame, val_list*); } 

#endif
