// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/snmp/types.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "types.bif.h"

namespace plugin { namespace Bro_SNMP {

void __bif_types_init(plugin::Plugin* plugin)
	{
	BifType::Record::SNMP::Header = internal_type("SNMP::Header")->AsRecordType();
	plugin->AddBifItem("SNMP::Header", plugin::BifItem::TYPE);
	BifType::Record::SNMP::HeaderV1 = internal_type("SNMP::HeaderV1")->AsRecordType();
	plugin->AddBifItem("SNMP::HeaderV1", plugin::BifItem::TYPE);
	BifType::Record::SNMP::HeaderV2 = internal_type("SNMP::HeaderV2")->AsRecordType();
	plugin->AddBifItem("SNMP::HeaderV2", plugin::BifItem::TYPE);
	BifType::Record::SNMP::HeaderV3 = internal_type("SNMP::HeaderV3")->AsRecordType();
	plugin->AddBifItem("SNMP::HeaderV3", plugin::BifItem::TYPE);
	BifType::Record::SNMP::PDU = internal_type("SNMP::PDU")->AsRecordType();
	plugin->AddBifItem("SNMP::PDU", plugin::BifItem::TYPE);
	BifType::Record::SNMP::TrapPDU = internal_type("SNMP::TrapPDU")->AsRecordType();
	plugin->AddBifItem("SNMP::TrapPDU", plugin::BifItem::TYPE);
	BifType::Record::SNMP::BulkPDU = internal_type("SNMP::BulkPDU")->AsRecordType();
	plugin->AddBifItem("SNMP::BulkPDU", plugin::BifItem::TYPE);
	BifType::Record::SNMP::ScopedPDU_Context = internal_type("SNMP::ScopedPDU_Context")->AsRecordType();
	plugin->AddBifItem("SNMP::ScopedPDU_Context", plugin::BifItem::TYPE);
	BifType::Record::SNMP::ObjectValue = internal_type("SNMP::ObjectValue")->AsRecordType();
	plugin->AddBifItem("SNMP::ObjectValue", plugin::BifItem::TYPE);
	BifType::Record::SNMP::Binding = internal_type("SNMP::Binding")->AsRecordType();
	plugin->AddBifItem("SNMP::Binding", plugin::BifItem::TYPE);
	BifType::Vector::SNMP::Bindings = internal_type("SNMP::Bindings")->AsVectorType();
	plugin->AddBifItem("SNMP::Bindings", plugin::BifItem::TYPE);

	}
} }


