// This file was automatically generated by bifcl from /home/ubuntu/bro/src/file_analysis/analyzer/hash/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_FileHash {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::file_hash = internal_handler("file_hash");
	plugin->AddBifItem("file_hash", plugin::BifItem::EVENT);

	}
} }


