// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/mysql/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_MySQL {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::mysql_command_request = internal_handler("mysql_command_request");
	plugin->AddBifItem("mysql_command_request", plugin::BifItem::EVENT);
	::mysql_error = internal_handler("mysql_error");
	plugin->AddBifItem("mysql_error", plugin::BifItem::EVENT);
	::mysql_ok = internal_handler("mysql_ok");
	plugin->AddBifItem("mysql_ok", plugin::BifItem::EVENT);
	::mysql_server_version = internal_handler("mysql_server_version");
	plugin->AddBifItem("mysql_server_version", plugin::BifItem::EVENT);
	::mysql_handshake = internal_handler("mysql_handshake");
	plugin->AddBifItem("mysql_handshake", plugin::BifItem::EVENT);

	}
} }


