// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/mysql/events.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_analyzer_protocol_mysql_events_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_mysql_events_bif
#define _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_mysql_events_bif
#include "bro-bif.h"
#endif
#endif

extern EventHandlerPtr mysql_command_request; 
namespace BifEvent {  void generate_mysql_command_request(analyzer::Analyzer* analyzer, Connection* c, bro_uint_t command, StringVal* arg);  } 
extern EventHandlerPtr mysql_error; 
namespace BifEvent {  void generate_mysql_error(analyzer::Analyzer* analyzer, Connection* c, bro_uint_t code, StringVal* msg);  } 
extern EventHandlerPtr mysql_ok; 
namespace BifEvent {  void generate_mysql_ok(analyzer::Analyzer* analyzer, Connection* c, bro_uint_t affected_rows);  } 
extern EventHandlerPtr mysql_server_version; 
namespace BifEvent {  void generate_mysql_server_version(analyzer::Analyzer* analyzer, Connection* c, StringVal* ver);  } 
extern EventHandlerPtr mysql_handshake; 
namespace BifEvent {  void generate_mysql_handshake(analyzer::Analyzer* analyzer, Connection* c, StringVal* username);  } 

#endif
