// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/ssh/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_SSH {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::ssh_server_version = internal_handler("ssh_server_version");
	plugin->AddBifItem("ssh_server_version", plugin::BifItem::EVENT);
	::ssh_client_version = internal_handler("ssh_client_version");
	plugin->AddBifItem("ssh_client_version", plugin::BifItem::EVENT);
	::ssh_auth_successful = internal_handler("ssh_auth_successful");
	plugin->AddBifItem("ssh_auth_successful", plugin::BifItem::EVENT);
	::ssh_auth_attempted = internal_handler("ssh_auth_attempted");
	plugin->AddBifItem("ssh_auth_attempted", plugin::BifItem::EVENT);
	::ssh_capabilities = internal_handler("ssh_capabilities");
	plugin->AddBifItem("ssh_capabilities", plugin::BifItem::EVENT);
	::ssh2_server_host_key = internal_handler("ssh2_server_host_key");
	plugin->AddBifItem("ssh2_server_host_key", plugin::BifItem::EVENT);
	::ssh1_server_host_key = internal_handler("ssh1_server_host_key");
	plugin->AddBifItem("ssh1_server_host_key", plugin::BifItem::EVENT);
	::ssh_encrypted_packet = internal_handler("ssh_encrypted_packet");
	plugin->AddBifItem("ssh_encrypted_packet", plugin::BifItem::EVENT);
	::ssh2_dh_server_params = internal_handler("ssh2_dh_server_params");
	plugin->AddBifItem("ssh2_dh_server_params", plugin::BifItem::EVENT);
	::ssh2_gss_error = internal_handler("ssh2_gss_error");
	plugin->AddBifItem("ssh2_gss_error", plugin::BifItem::EVENT);
	::ssh2_ecc_key = internal_handler("ssh2_ecc_key");
	plugin->AddBifItem("ssh2_ecc_key", plugin::BifItem::EVENT);

	}
} }


