// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/ssh/types.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_SSH {
void __bif_types_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_SSH_types("Bro::SSH", __bif_types_init);
} }
