// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/radius/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_RADIUS {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_RADIUS_events("Bro::RADIUS", __bif_events_init);
} }
