// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/radius/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_RADIUS {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::radius_message = internal_handler("radius_message");
	plugin->AddBifItem("radius_message", plugin::BifItem::EVENT);
	::radius_attribute = internal_handler("radius_attribute");
	plugin->AddBifItem("radius_attribute", plugin::BifItem::EVENT);
	BifType::Vector::RADIUS::AttributeList = internal_type("RADIUS::AttributeList")->AsVectorType();
	plugin->AddBifItem("RADIUS::AttributeList", plugin::BifItem::TYPE);
	BifType::Table::RADIUS::Attributes = internal_type("RADIUS::Attributes")->AsTableType();
	plugin->AddBifItem("RADIUS::Attributes", plugin::BifItem::TYPE);
	BifType::Record::RADIUS::Message = internal_type("RADIUS::Message")->AsRecordType();
	plugin->AddBifItem("RADIUS::Message", plugin::BifItem::TYPE);

	}
} }


