// This file was automatically generated by bifcl from /home/ubuntu/bro/src/file_analysis/analyzer/extract/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_FileExtract {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_FileExtract_events("Bro::FileExtract", __bif_events_init);
} }
