// This file was automatically generated by bifcl from /home/ubuntu/bro/src/file_analysis/analyzer/extract/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_FileExtract {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::file_extraction_limit = internal_handler("file_extraction_limit");
	plugin->AddBifItem("file_extraction_limit", plugin::BifItem::EVENT);

	}
} }


