// This file was automatically generated by bifcl from /home/ubuntu/bro/src/file_analysis/analyzer/extract/functions.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "functions.bif.h"

namespace plugin { namespace Bro_FileExtract {

void __bif_functions_init(plugin::Plugin* plugin)
	{
	(void) new BuiltinFunc(BifFunc::FileExtract::bro___set_limit, "FileExtract::__set_limit", 0);
	plugin->AddBifItem("FileExtract::__set_limit", plugin::BifItem::FUNCTION);

	}
} }


