// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/gssapi/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_GSSAPI {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::gssapi_neg_result = internal_handler("gssapi_neg_result");
	plugin->AddBifItem("gssapi_neg_result", plugin::BifItem::EVENT);

	}
} }


