// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/gssapi/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_GSSAPI {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_GSSAPI_events("Bro::GSSAPI", __bif_events_init);
} }
