// This file was automatically generated by bifcl from /home/ubuntu/bro/src/broxygen/broxygen.bif (alternative mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_broxygen_broxygen_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_broxygen_broxygen_bif
#define _home_ubuntu_bro_my_build_dir_src_broxygen_broxygen_bif
#include "bro-bif.h"
#endif
#endif

namespace BifFunc { extern Val* bro_get_identifier_comments(Frame* frame, val_list*); } 
namespace BifFunc { extern Val* bro_get_script_comments(Frame* frame, val_list*); } 
namespace BifFunc { extern Val* bro_get_package_readme(Frame* frame, val_list*); } 
namespace BifFunc { extern Val* bro_get_record_field_comments(Frame* frame, val_list*); } 

#endif
