// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/xmpp/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_XMPP {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_XMPP_events("Bro::XMPP", __bif_events_init);
} }
