// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/xmpp/events.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_analyzer_protocol_xmpp_events_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_xmpp_events_bif
#define _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_xmpp_events_bif
#include "bro-bif.h"
#endif
#endif

extern EventHandlerPtr xmpp_starttls; 
namespace BifEvent {  void generate_xmpp_starttls(analyzer::Analyzer* analyzer, Connection* c);  } 

#endif
