// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/xmpp/events.bif (plugin mode).


#include "events.bif.h"

EventHandlerPtr xmpp_starttls; 
void BifEvent::generate_xmpp_starttls(analyzer::Analyzer* analyzer, Connection* c)
	{
	// Note that it is intentional that here we do not
	// check if ::xmpp_starttls is NULL, which should happen *before*
	// BifEvent::generate_xmpp_starttls is called to avoid unnecessary Val
	// allocation.

	val_list* vl = new val_list;

	vl->append(c->BuildConnVal());

	mgr.QueueEvent(::xmpp_starttls, vl, SOURCE_LOCAL, analyzer->GetID(), timer_mgr, c);
	} // event generation
