// This file was automatically generated by bifcl from /home/ubuntu/bro/src/input/readers/raw/raw.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_RawReader {
void __bif_raw_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_RawReader_raw("Bro::RawReader", __bif_raw_init);
} }
