// This file was automatically generated by bifcl from /home/ubuntu/bro/src/input/readers/raw/raw.bif (plugin mode).


#include "raw.bif.h"

namespace BifConst { namespace InputRaw {  StringVal* record_separator;  }  }
