// This file was automatically generated by bifcl from /home/ubuntu/bro/src/file_analysis/analyzer/x509/events.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_file_analysis_analyzer_x509_events_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_file_analysis_analyzer_x509_events_bif
#define _home_ubuntu_bro_my_build_dir_src_file_analysis_analyzer_x509_events_bif
#include "bro-bif.h"
#endif
#endif

extern EventHandlerPtr x509_certificate; 
namespace BifEvent {  void generate_x509_certificate(analyzer::Analyzer* analyzer, Val* f, Val* cert_ref, Val* cert);  } 
extern EventHandlerPtr x509_extension; 
namespace BifEvent {  void generate_x509_extension(analyzer::Analyzer* analyzer, Val* f, Val* ext);  } 
extern EventHandlerPtr x509_ext_basic_constraints; 
namespace BifEvent {  void generate_x509_ext_basic_constraints(analyzer::Analyzer* analyzer, Val* f, Val* ext);  } 
extern EventHandlerPtr x509_ext_subject_alternative_name; 
namespace BifEvent {  void generate_x509_ext_subject_alternative_name(analyzer::Analyzer* analyzer, Val* f, Val* ext);  } 
extern EventHandlerPtr x509_ocsp_ext_signed_certificate_timestamp; 
namespace BifEvent {  void generate_x509_ocsp_ext_signed_certificate_timestamp(analyzer::Analyzer* analyzer, Val* f, bro_uint_t version, StringVal* logid, bro_uint_t timestamp, bro_uint_t hash_algorithm, bro_uint_t signature_algorithm, StringVal* signature);  } 

#endif
