// This file was automatically generated by bifcl from /home/ubuntu/bro/src/file_analysis/analyzer/x509/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_X509 {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::x509_certificate = internal_handler("x509_certificate");
	plugin->AddBifItem("x509_certificate", plugin::BifItem::EVENT);
	::x509_extension = internal_handler("x509_extension");
	plugin->AddBifItem("x509_extension", plugin::BifItem::EVENT);
	::x509_ext_basic_constraints = internal_handler("x509_ext_basic_constraints");
	plugin->AddBifItem("x509_ext_basic_constraints", plugin::BifItem::EVENT);
	::x509_ext_subject_alternative_name = internal_handler("x509_ext_subject_alternative_name");
	plugin->AddBifItem("x509_ext_subject_alternative_name", plugin::BifItem::EVENT);
	::x509_ocsp_ext_signed_certificate_timestamp = internal_handler("x509_ocsp_ext_signed_certificate_timestamp");
	plugin->AddBifItem("x509_ocsp_ext_signed_certificate_timestamp", plugin::BifItem::EVENT);

	}
} }


