// This file was automatically generated by bifcl from /home/ubuntu/bro/src/file_analysis/analyzer/x509/functions.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_X509 {
void __bif_functions_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_X509_functions("Bro::X509", __bif_functions_init);
} }
