// This file was automatically generated by bifcl from /home/ubuntu/bro/src/file_analysis/analyzer/x509/ocsp_events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "ocsp_events.bif.h"

namespace plugin { namespace Bro_X509 {

void __bif_ocsp_events_init(plugin::Plugin* plugin)
	{
	::ocsp_request = internal_handler("ocsp_request");
	plugin->AddBifItem("ocsp_request", plugin::BifItem::EVENT);
	::ocsp_request_certificate = internal_handler("ocsp_request_certificate");
	plugin->AddBifItem("ocsp_request_certificate", plugin::BifItem::EVENT);
	::ocsp_response_status = internal_handler("ocsp_response_status");
	plugin->AddBifItem("ocsp_response_status", plugin::BifItem::EVENT);
	::ocsp_response_bytes = internal_handler("ocsp_response_bytes");
	plugin->AddBifItem("ocsp_response_bytes", plugin::BifItem::EVENT);
	::ocsp_response_certificate = internal_handler("ocsp_response_certificate");
	plugin->AddBifItem("ocsp_response_certificate", plugin::BifItem::EVENT);
	::ocsp_extension = internal_handler("ocsp_extension");
	plugin->AddBifItem("ocsp_extension", plugin::BifItem::EVENT);

	}
} }


