// This file was automatically generated by bifcl from /home/ubuntu/bro/src/file_analysis/analyzer/x509/types.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_file_analysis_analyzer_x509_types_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_file_analysis_analyzer_x509_types_bif
#define _home_ubuntu_bro_my_build_dir_src_file_analysis_analyzer_x509_types_bif
#include "bro-bif.h"
#endif
#endif

namespace BifType { namespace Record{ namespace X509 {  extern RecordType * Certificate;  } } }
namespace BifType { namespace Record{ namespace X509 {  extern RecordType * Extension;  } } }
namespace BifType { namespace Record{ namespace X509 {  extern RecordType * BasicConstraints;  } } }
namespace BifType { namespace Record{ namespace X509 {  extern RecordType * SubjectAlternativeName;  } } }
namespace BifType { namespace Record{ namespace X509 {  extern RecordType * Result;  } } }

#endif
