// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/udp/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_UDP {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::udp_request = internal_handler("udp_request");
	plugin->AddBifItem("udp_request", plugin::BifItem::EVENT);
	::udp_reply = internal_handler("udp_reply");
	plugin->AddBifItem("udp_reply", plugin::BifItem::EVENT);
	::udp_contents = internal_handler("udp_contents");
	plugin->AddBifItem("udp_contents", plugin::BifItem::EVENT);

	}
} }


