// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/udp/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_UDP {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_UDP_events("Bro::UDP", __bif_events_init);
} }
