// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/krb/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_KRB {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_KRB_events("Bro::KRB", __bif_events_init);
} }
