// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/ssl/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_SSL {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::ssl_client_hello = internal_handler("ssl_client_hello");
	plugin->AddBifItem("ssl_client_hello", plugin::BifItem::EVENT);
	::ssl_server_hello = internal_handler("ssl_server_hello");
	plugin->AddBifItem("ssl_server_hello", plugin::BifItem::EVENT);
	::ssl_extension = internal_handler("ssl_extension");
	plugin->AddBifItem("ssl_extension", plugin::BifItem::EVENT);
	::ssl_extension_elliptic_curves = internal_handler("ssl_extension_elliptic_curves");
	plugin->AddBifItem("ssl_extension_elliptic_curves", plugin::BifItem::EVENT);
	::ssl_extension_ec_point_formats = internal_handler("ssl_extension_ec_point_formats");
	plugin->AddBifItem("ssl_extension_ec_point_formats", plugin::BifItem::EVENT);
	::ssl_extension_signature_algorithm = internal_handler("ssl_extension_signature_algorithm");
	plugin->AddBifItem("ssl_extension_signature_algorithm", plugin::BifItem::EVENT);
	::ssl_extension_key_share = internal_handler("ssl_extension_key_share");
	plugin->AddBifItem("ssl_extension_key_share", plugin::BifItem::EVENT);
	::ssl_server_curve = internal_handler("ssl_server_curve");
	plugin->AddBifItem("ssl_server_curve", plugin::BifItem::EVENT);
	::ssl_ecdh_server_params = internal_handler("ssl_ecdh_server_params");
	plugin->AddBifItem("ssl_ecdh_server_params", plugin::BifItem::EVENT);
	::ssl_dh_server_params = internal_handler("ssl_dh_server_params");
	plugin->AddBifItem("ssl_dh_server_params", plugin::BifItem::EVENT);
	::ssl_server_signature = internal_handler("ssl_server_signature");
	plugin->AddBifItem("ssl_server_signature", plugin::BifItem::EVENT);
	::ssl_ecdh_client_params = internal_handler("ssl_ecdh_client_params");
	plugin->AddBifItem("ssl_ecdh_client_params", plugin::BifItem::EVENT);
	::ssl_dh_client_params = internal_handler("ssl_dh_client_params");
	plugin->AddBifItem("ssl_dh_client_params", plugin::BifItem::EVENT);
	::ssl_rsa_client_pms = internal_handler("ssl_rsa_client_pms");
	plugin->AddBifItem("ssl_rsa_client_pms", plugin::BifItem::EVENT);
	::ssl_extension_application_layer_protocol_negotiation = internal_handler("ssl_extension_application_layer_protocol_negotiation");
	plugin->AddBifItem("ssl_extension_application_layer_protocol_negotiation", plugin::BifItem::EVENT);
	::ssl_extension_server_name = internal_handler("ssl_extension_server_name");
	plugin->AddBifItem("ssl_extension_server_name", plugin::BifItem::EVENT);
	::ssl_extension_signed_certificate_timestamp = internal_handler("ssl_extension_signed_certificate_timestamp");
	plugin->AddBifItem("ssl_extension_signed_certificate_timestamp", plugin::BifItem::EVENT);
	::ssl_extension_supported_versions = internal_handler("ssl_extension_supported_versions");
	plugin->AddBifItem("ssl_extension_supported_versions", plugin::BifItem::EVENT);
	::ssl_extension_psk_key_exchange_modes = internal_handler("ssl_extension_psk_key_exchange_modes");
	plugin->AddBifItem("ssl_extension_psk_key_exchange_modes", plugin::BifItem::EVENT);
	::ssl_established = internal_handler("ssl_established");
	plugin->AddBifItem("ssl_established", plugin::BifItem::EVENT);
	::ssl_alert = internal_handler("ssl_alert");
	plugin->AddBifItem("ssl_alert", plugin::BifItem::EVENT);
	::ssl_session_ticket_handshake = internal_handler("ssl_session_ticket_handshake");
	plugin->AddBifItem("ssl_session_ticket_handshake", plugin::BifItem::EVENT);
	::ssl_heartbeat = internal_handler("ssl_heartbeat");
	plugin->AddBifItem("ssl_heartbeat", plugin::BifItem::EVENT);
	::ssl_application_data = internal_handler("ssl_application_data");
	plugin->AddBifItem("ssl_application_data", plugin::BifItem::EVENT);
	::ssl_encrypted_data = internal_handler("ssl_encrypted_data");
	plugin->AddBifItem("ssl_encrypted_data", plugin::BifItem::EVENT);
	::ssl_stapled_ocsp = internal_handler("ssl_stapled_ocsp");
	plugin->AddBifItem("ssl_stapled_ocsp", plugin::BifItem::EVENT);
	::ssl_handshake_message = internal_handler("ssl_handshake_message");
	plugin->AddBifItem("ssl_handshake_message", plugin::BifItem::EVENT);
	::ssl_change_cipher_spec = internal_handler("ssl_change_cipher_spec");
	plugin->AddBifItem("ssl_change_cipher_spec", plugin::BifItem::EVENT);

	}
} }


