// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/ssl/functions.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_SSL {
void __bif_functions_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_SSL_functions("Bro::SSL", __bif_functions_init);
} }
