// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/ssl/functions.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_analyzer_protocol_ssl_functions_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_ssl_functions_bif
#define _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_ssl_functions_bif
#include "bro-bif.h"
#endif
#endif

namespace BifFunc { extern Val* bro_set_ssl_established(Frame* frame, val_list*); } 

#endif
