// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/arp/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_ARP {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::arp_request = internal_handler("arp_request");
	plugin->AddBifItem("arp_request", plugin::BifItem::EVENT);
	::arp_reply = internal_handler("arp_reply");
	plugin->AddBifItem("arp_reply", plugin::BifItem::EVENT);
	::bad_arp = internal_handler("bad_arp");
	plugin->AddBifItem("bad_arp", plugin::BifItem::EVENT);

	}
} }


