// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/dns/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_DNS {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::dns_message = internal_handler("dns_message");
	plugin->AddBifItem("dns_message", plugin::BifItem::EVENT);
	::dns_request = internal_handler("dns_request");
	plugin->AddBifItem("dns_request", plugin::BifItem::EVENT);
	::dns_rejected = internal_handler("dns_rejected");
	plugin->AddBifItem("dns_rejected", plugin::BifItem::EVENT);
	::dns_query_reply = internal_handler("dns_query_reply");
	plugin->AddBifItem("dns_query_reply", plugin::BifItem::EVENT);
	::dns_A_reply = internal_handler("dns_A_reply");
	plugin->AddBifItem("dns_A_reply", plugin::BifItem::EVENT);
	::dns_AAAA_reply = internal_handler("dns_AAAA_reply");
	plugin->AddBifItem("dns_AAAA_reply", plugin::BifItem::EVENT);
	::dns_A6_reply = internal_handler("dns_A6_reply");
	plugin->AddBifItem("dns_A6_reply", plugin::BifItem::EVENT);
	::dns_NS_reply = internal_handler("dns_NS_reply");
	plugin->AddBifItem("dns_NS_reply", plugin::BifItem::EVENT);
	::dns_CNAME_reply = internal_handler("dns_CNAME_reply");
	plugin->AddBifItem("dns_CNAME_reply", plugin::BifItem::EVENT);
	::dns_PTR_reply = internal_handler("dns_PTR_reply");
	plugin->AddBifItem("dns_PTR_reply", plugin::BifItem::EVENT);
	::dns_SOA_reply = internal_handler("dns_SOA_reply");
	plugin->AddBifItem("dns_SOA_reply", plugin::BifItem::EVENT);
	::dns_WKS_reply = internal_handler("dns_WKS_reply");
	plugin->AddBifItem("dns_WKS_reply", plugin::BifItem::EVENT);
	::dns_HINFO_reply = internal_handler("dns_HINFO_reply");
	plugin->AddBifItem("dns_HINFO_reply", plugin::BifItem::EVENT);
	::dns_MX_reply = internal_handler("dns_MX_reply");
	plugin->AddBifItem("dns_MX_reply", plugin::BifItem::EVENT);
	::dns_TXT_reply = internal_handler("dns_TXT_reply");
	plugin->AddBifItem("dns_TXT_reply", plugin::BifItem::EVENT);
	::dns_CAA_reply = internal_handler("dns_CAA_reply");
	plugin->AddBifItem("dns_CAA_reply", plugin::BifItem::EVENT);
	::dns_SRV_reply = internal_handler("dns_SRV_reply");
	plugin->AddBifItem("dns_SRV_reply", plugin::BifItem::EVENT);
	::dns_unknown_reply = internal_handler("dns_unknown_reply");
	plugin->AddBifItem("dns_unknown_reply", plugin::BifItem::EVENT);
	::dns_EDNS_addl = internal_handler("dns_EDNS_addl");
	plugin->AddBifItem("dns_EDNS_addl", plugin::BifItem::EVENT);
	::dns_TSIG_addl = internal_handler("dns_TSIG_addl");
	plugin->AddBifItem("dns_TSIG_addl", plugin::BifItem::EVENT);
	::dns_end = internal_handler("dns_end");
	plugin->AddBifItem("dns_end", plugin::BifItem::EVENT);
	::dns_full_request = internal_handler("dns_full_request");
	plugin->AddBifItem("dns_full_request", plugin::BifItem::EVENT);
	::non_dns_request = internal_handler("non_dns_request");
	plugin->AddBifItem("non_dns_request", plugin::BifItem::EVENT);

	}
} }


