// This file was automatically generated by bifcl from /home/ubuntu/bro/src/file_analysis/file_analysis.bif (alternative mode).

	BifType::Record::Files::AnalyzerArgs = internal_type("Files::AnalyzerArgs")->AsRecordType();
	(void) new BuiltinFunc(BifFunc::Files::bro___set_timeout_interval, "Files::__set_timeout_interval", 0);
	(void) new BuiltinFunc(BifFunc::Files::bro___enable_reassembly, "Files::__enable_reassembly", 0);
	(void) new BuiltinFunc(BifFunc::Files::bro___disable_reassembly, "Files::__disable_reassembly", 0);
	(void) new BuiltinFunc(BifFunc::Files::bro___set_reassembly_buffer, "Files::__set_reassembly_buffer", 0);
	(void) new BuiltinFunc(BifFunc::Files::bro___add_analyzer, "Files::__add_analyzer", 0);
	(void) new BuiltinFunc(BifFunc::Files::bro___remove_analyzer, "Files::__remove_analyzer", 0);
	(void) new BuiltinFunc(BifFunc::Files::bro___stop, "Files::__stop", 0);
	(void) new BuiltinFunc(BifFunc::Files::bro___analyzer_name, "Files::__analyzer_name", 0);
	(void) new BuiltinFunc(BifFunc::Files::bro___file_exists, "Files::__file_exists", 0);
	(void) new BuiltinFunc(BifFunc::Files::bro___lookup_file, "Files::__lookup_file", 0);
	(void) new BuiltinFunc(BifFunc::bro_set_file_handle, "set_file_handle", 0);
	BifConst::Files::salt = internal_const_val("Files::salt")->AsStringVal();
