// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/netbios/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_NetBIOS {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_NetBIOS_events("Bro::NetBIOS", __bif_events_init);
} }
