// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/netbios/functions.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_NetBIOS {
void __bif_functions_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_NetBIOS_functions("Bro::NetBIOS", __bif_functions_init);
} }
