// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/syslog/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_Syslog {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_Syslog_events("Bro::Syslog", __bif_events_init);
} }
