// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/syslog/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_Syslog {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::syslog_message = internal_handler("syslog_message");
	plugin->AddBifItem("syslog_message", plugin::BifItem::EVENT);

	}
} }


