// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/conn-size/events.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_analyzer_protocol_conn_size_events_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_conn_size_events_bif
#define _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_conn_size_events_bif
#include "bro-bif.h"
#endif
#endif

extern EventHandlerPtr conn_bytes_threshold_crossed; 
namespace BifEvent {  void generate_conn_bytes_threshold_crossed(analyzer::Analyzer* analyzer, Connection* c, bro_uint_t threshold, int is_orig);  } 
extern EventHandlerPtr conn_packets_threshold_crossed; 
namespace BifEvent {  void generate_conn_packets_threshold_crossed(analyzer::Analyzer* analyzer, Connection* c, bro_uint_t threshold, int is_orig);  } 

#endif
