// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/conn-size/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_ConnSize {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_ConnSize_events("Bro::ConnSize", __bif_events_init);
} }
