// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/conn-size/functions.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_ConnSize {
void __bif_functions_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_ConnSize_functions("Bro::ConnSize", __bif_functions_init);
} }
