// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/conn-size/functions.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "functions.bif.h"

namespace plugin { namespace Bro_ConnSize {

void __bif_functions_init(plugin::Plugin* plugin)
	{
	(void) new BuiltinFunc(BifFunc::bro_set_current_conn_bytes_threshold, "set_current_conn_bytes_threshold", 0);
	plugin->AddBifItem("set_current_conn_bytes_threshold", plugin::BifItem::FUNCTION);
	(void) new BuiltinFunc(BifFunc::bro_set_current_conn_packets_threshold, "set_current_conn_packets_threshold", 0);
	plugin->AddBifItem("set_current_conn_packets_threshold", plugin::BifItem::FUNCTION);
	(void) new BuiltinFunc(BifFunc::bro_get_current_conn_bytes_threshold, "get_current_conn_bytes_threshold", 0);
	plugin->AddBifItem("get_current_conn_bytes_threshold", plugin::BifItem::FUNCTION);
	(void) new BuiltinFunc(BifFunc::bro_get_current_conn_packets_threshold, "get_current_conn_packets_threshold", 0);
	plugin->AddBifItem("get_current_conn_packets_threshold", plugin::BifItem::FUNCTION);

	}
} }


