// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/ntp/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_NTP {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_NTP_events("Bro::NTP", __bif_events_init);
} }
