// This file was automatically generated by bifcl from /home/ubuntu/bro/src/input/readers/config/config.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "config.bif.h"

namespace plugin { namespace Bro_ConfigReader {

void __bif_config_init(plugin::Plugin* plugin)
	{
	BifConst::InputConfig::set_separator = internal_const_val("InputConfig::set_separator")->AsStringVal();
	plugin->AddBifItem("InputConfig::set_separator", plugin::BifItem::CONSTANT);
	BifConst::InputConfig::empty_field = internal_const_val("InputConfig::empty_field")->AsStringVal();
	plugin->AddBifItem("InputConfig::empty_field", plugin::BifItem::CONSTANT);
	BifConst::InputConfig::fail_on_file_problem = internal_const_val("InputConfig::fail_on_file_problem")->AsBool();
	plugin->AddBifItem("InputConfig::fail_on_file_problem", plugin::BifItem::CONSTANT);

	}
} }


