// This file was automatically generated by bifcl from /home/ubuntu/bro/src/input/readers/config/config.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_ConfigReader {
void __bif_config_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_ConfigReader_config("Bro::ConfigReader", __bif_config_init);
} }
