// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/pop3/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_POP3 {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_POP3_events("Bro::POP3", __bif_events_init);
} }
