// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/pop3/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_POP3 {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::pop3_request = internal_handler("pop3_request");
	plugin->AddBifItem("pop3_request", plugin::BifItem::EVENT);
	::pop3_reply = internal_handler("pop3_reply");
	plugin->AddBifItem("pop3_reply", plugin::BifItem::EVENT);
	::pop3_data = internal_handler("pop3_data");
	plugin->AddBifItem("pop3_data", plugin::BifItem::EVENT);
	::pop3_unexpected = internal_handler("pop3_unexpected");
	plugin->AddBifItem("pop3_unexpected", plugin::BifItem::EVENT);
	::pop3_starttls = internal_handler("pop3_starttls");
	plugin->AddBifItem("pop3_starttls", plugin::BifItem::EVENT);
	::pop3_login_success = internal_handler("pop3_login_success");
	plugin->AddBifItem("pop3_login_success", plugin::BifItem::EVENT);
	::pop3_login_failure = internal_handler("pop3_login_failure");
	plugin->AddBifItem("pop3_login_failure", plugin::BifItem::EVENT);

	}
} }


