// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/socks/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_SOCKS {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_SOCKS_events("Bro::SOCKS", __bif_events_init);
} }
