// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/ftp/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_FTP {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_FTP_events("Bro::FTP", __bif_events_init);
} }
