// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/ftp/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_FTP {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::ftp_request = internal_handler("ftp_request");
	plugin->AddBifItem("ftp_request", plugin::BifItem::EVENT);
	::ftp_reply = internal_handler("ftp_reply");
	plugin->AddBifItem("ftp_reply", plugin::BifItem::EVENT);

	}
} }


