// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/ftp/functions.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_FTP {
void __bif_functions_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_FTP_functions("Bro::FTP", __bif_functions_init);
} }
