// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/ftp/functions.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "functions.bif.h"

namespace plugin { namespace Bro_FTP {

void __bif_functions_init(plugin::Plugin* plugin)
	{
	BifType::Record::ftp_port = internal_type("ftp_port")->AsRecordType();
	plugin->AddBifItem("ftp_port", plugin::BifItem::TYPE);
	(void) new BuiltinFunc(BifFunc::bro_parse_ftp_port, "parse_ftp_port", 0);
	plugin->AddBifItem("parse_ftp_port", plugin::BifItem::FUNCTION);
	(void) new BuiltinFunc(BifFunc::bro_parse_eftp_port, "parse_eftp_port", 0);
	plugin->AddBifItem("parse_eftp_port", plugin::BifItem::FUNCTION);
	(void) new BuiltinFunc(BifFunc::bro_parse_ftp_pasv, "parse_ftp_pasv", 0);
	plugin->AddBifItem("parse_ftp_pasv", plugin::BifItem::FUNCTION);
	(void) new BuiltinFunc(BifFunc::bro_parse_ftp_epsv, "parse_ftp_epsv", 0);
	plugin->AddBifItem("parse_ftp_epsv", plugin::BifItem::FUNCTION);
	(void) new BuiltinFunc(BifFunc::bro_fmt_ftp_port, "fmt_ftp_port", 0);
	plugin->AddBifItem("fmt_ftp_port", plugin::BifItem::FUNCTION);

	}
} }


