// This file was automatically generated by bifcl from /home/ubuntu/bro/src/file_analysis/analyzer/unified2/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_Unified2 {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::unified2_event = internal_handler("unified2_event");
	plugin->AddBifItem("unified2_event", plugin::BifItem::EVENT);
	::unified2_packet = internal_handler("unified2_packet");
	plugin->AddBifItem("unified2_packet", plugin::BifItem::EVENT);

	}
} }


