// This file was automatically generated by bifcl from /home/ubuntu/bro/src/file_analysis/analyzer/unified2/types.bif (plugin mode).


#include "types.bif.h"

namespace BifType { namespace Record{ namespace Unified2 {  RecordType * IDSEvent;  } } }
namespace BifType { namespace Record{ namespace Unified2 {  RecordType * Packet;  } } }
