// This file was automatically generated by bifcl from /home/ubuntu/bro/src/file_analysis/analyzer/unified2/types.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_Unified2 {
void __bif_types_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_Unified2_types("Bro::Unified2", __bif_types_init);
} }
