// This file was automatically generated by bifcl from /home/ubuntu/bro/src/input/readers/binary/binary.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "binary.bif.h"

namespace plugin { namespace Bro_BinaryReader {

void __bif_binary_init(plugin::Plugin* plugin)
	{
	BifConst::InputBinary::chunk_size = internal_const_val("InputBinary::chunk_size")->AsCount();
	plugin->AddBifItem("InputBinary::chunk_size", plugin::BifItem::CONSTANT);

	}
} }


