// This file was automatically generated by bifcl from /home/ubuntu/bro/src/input/readers/binary/binary.bif (plugin mode).


#include "binary.bif.h"

namespace BifConst { namespace InputBinary {  bro_uint_t chunk_size;  }  }
