// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/backdoor/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_BackDoor {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::backdoor_stats = internal_handler("backdoor_stats");
	plugin->AddBifItem("backdoor_stats", plugin::BifItem::EVENT);
	::backdoor_remove_conn = internal_handler("backdoor_remove_conn");
	plugin->AddBifItem("backdoor_remove_conn", plugin::BifItem::EVENT);
	::ftp_signature_found = internal_handler("ftp_signature_found");
	plugin->AddBifItem("ftp_signature_found", plugin::BifItem::EVENT);
	::gnutella_signature_found = internal_handler("gnutella_signature_found");
	plugin->AddBifItem("gnutella_signature_found", plugin::BifItem::EVENT);
	::http_signature_found = internal_handler("http_signature_found");
	plugin->AddBifItem("http_signature_found", plugin::BifItem::EVENT);
	::irc_signature_found = internal_handler("irc_signature_found");
	plugin->AddBifItem("irc_signature_found", plugin::BifItem::EVENT);
	::telnet_signature_found = internal_handler("telnet_signature_found");
	plugin->AddBifItem("telnet_signature_found", plugin::BifItem::EVENT);
	::ssh_signature_found = internal_handler("ssh_signature_found");
	plugin->AddBifItem("ssh_signature_found", plugin::BifItem::EVENT);
	::rlogin_signature_found = internal_handler("rlogin_signature_found");
	plugin->AddBifItem("rlogin_signature_found", plugin::BifItem::EVENT);
	::smtp_signature_found = internal_handler("smtp_signature_found");
	plugin->AddBifItem("smtp_signature_found", plugin::BifItem::EVENT);
	::http_proxy_signature_found = internal_handler("http_proxy_signature_found");
	plugin->AddBifItem("http_proxy_signature_found", plugin::BifItem::EVENT);

	}
} }


