# This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/krb/types.bif (plugin mode).

export {
module KRB;
















module GLOBAL;

} # end of export section
module GLOBAL;
