# This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/interconn/events.bif (plugin mode).



## Deprecated. Will be removed.
export {
global interconn_stats: event(c: connection , os: interconn_endp_stats , rs: interconn_endp_stats );


## Deprecated. Will be removed.
global interconn_remove_conn: event(c: connection );


} # end of export section
module GLOBAL;
