// This file was automatically generated by bifcl from /home/ubuntu/bro/src/input/readers/sqlite/sqlite.bif (plugin mode).


#include "sqlite.bif.h"

namespace BifConst { namespace InputSQLite {  StringVal* set_separator;  }  }
namespace BifConst { namespace InputSQLite {  StringVal* unset_field;  }  }
namespace BifConst { namespace InputSQLite {  StringVal* empty_field;  }  }
