// This file was automatically generated by bifcl from /home/ubuntu/bro/src/input/readers/sqlite/sqlite.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "sqlite.bif.h"

namespace plugin { namespace Bro_SQLiteReader {

void __bif_sqlite_init(plugin::Plugin* plugin)
	{
	BifConst::InputSQLite::set_separator = internal_const_val("InputSQLite::set_separator")->AsStringVal();
	plugin->AddBifItem("InputSQLite::set_separator", plugin::BifItem::CONSTANT);
	BifConst::InputSQLite::unset_field = internal_const_val("InputSQLite::unset_field")->AsStringVal();
	plugin->AddBifItem("InputSQLite::unset_field", plugin::BifItem::CONSTANT);
	BifConst::InputSQLite::empty_field = internal_const_val("InputSQLite::empty_field")->AsStringVal();
	plugin->AddBifItem("InputSQLite::empty_field", plugin::BifItem::CONSTANT);

	}
} }


