// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/http/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_HTTP {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_HTTP_events("Bro::HTTP", __bif_events_init);
} }
