// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/http/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_HTTP {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::http_request = internal_handler("http_request");
	plugin->AddBifItem("http_request", plugin::BifItem::EVENT);
	::http_reply = internal_handler("http_reply");
	plugin->AddBifItem("http_reply", plugin::BifItem::EVENT);
	::http_header = internal_handler("http_header");
	plugin->AddBifItem("http_header", plugin::BifItem::EVENT);
	::http_all_headers = internal_handler("http_all_headers");
	plugin->AddBifItem("http_all_headers", plugin::BifItem::EVENT);
	::http_begin_entity = internal_handler("http_begin_entity");
	plugin->AddBifItem("http_begin_entity", plugin::BifItem::EVENT);
	::http_end_entity = internal_handler("http_end_entity");
	plugin->AddBifItem("http_end_entity", plugin::BifItem::EVENT);
	::http_entity_data = internal_handler("http_entity_data");
	plugin->AddBifItem("http_entity_data", plugin::BifItem::EVENT);
	::http_content_type = internal_handler("http_content_type");
	plugin->AddBifItem("http_content_type", plugin::BifItem::EVENT);
	::http_message_done = internal_handler("http_message_done");
	plugin->AddBifItem("http_message_done", plugin::BifItem::EVENT);
	::http_event = internal_handler("http_event");
	plugin->AddBifItem("http_event", plugin::BifItem::EVENT);
	::http_stats = internal_handler("http_stats");
	plugin->AddBifItem("http_stats", plugin::BifItem::EVENT);
	::http_connection_upgrade = internal_handler("http_connection_upgrade");
	plugin->AddBifItem("http_connection_upgrade", plugin::BifItem::EVENT);

	}
} }


