// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/http/functions.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "functions.bif.h"

namespace plugin { namespace Bro_HTTP {

void __bif_functions_init(plugin::Plugin* plugin)
	{
	(void) new BuiltinFunc(BifFunc::bro_skip_http_entity_data, "skip_http_entity_data", 0);
	plugin->AddBifItem("skip_http_entity_data", plugin::BifItem::FUNCTION);
	(void) new BuiltinFunc(BifFunc::bro_unescape_URI, "unescape_URI", 0);
	plugin->AddBifItem("unescape_URI", plugin::BifItem::FUNCTION);

	}
} }


