// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/http/functions.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_HTTP {
void __bif_functions_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_HTTP_functions("Bro::HTTP", __bif_functions_init);
} }
