// This file was automatically generated by bifcl from /home/ubuntu/bro/src/input/readers/ascii/ascii.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_AsciiReader {
void __bif_ascii_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_AsciiReader_ascii("Bro::AsciiReader", __bif_ascii_init);
} }
