// This file was automatically generated by bifcl from /home/ubuntu/bro/src/input/readers/ascii/ascii.bif (plugin mode).


#include "ascii.bif.h"

namespace BifConst { namespace InputAscii {  StringVal* separator;  }  }
namespace BifConst { namespace InputAscii {  StringVal* set_separator;  }  }
namespace BifConst { namespace InputAscii {  StringVal* empty_field;  }  }
namespace BifConst { namespace InputAscii {  StringVal* unset_field;  }  }
namespace BifConst { namespace InputAscii {  int fail_on_invalid_lines;  }  }
namespace BifConst { namespace InputAscii {  int fail_on_file_problem;  }  }
