// This file was automatically generated by bifcl from /home/ubuntu/bro/src/file_analysis/analyzer/entropy/events.bif (plugin mode).


#include "events.bif.h"

EventHandlerPtr file_entropy; 
void BifEvent::generate_file_entropy(analyzer::Analyzer* analyzer, Val* f, Val* ent)
	{
	// Note that it is intentional that here we do not
	// check if ::file_entropy is NULL, which should happen *before*
	// BifEvent::generate_file_entropy is called to avoid unnecessary Val
	// allocation.

	val_list* vl = new val_list;

	vl->append(f);
	vl->append(ent);

	mgr.QueueEvent(::file_entropy, vl, SOURCE_LOCAL, analyzer->GetID(), timer_mgr);
	} // event generation
