// This file was automatically generated by bifcl from /home/ubuntu/bro/src/file_analysis/analyzer/entropy/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_FileEntropy {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_FileEntropy_events("Bro::FileEntropy", __bif_events_init);
} }
