// This file was automatically generated by bifcl from /home/ubuntu/bro/src/input/input.bif (alternative mode).

	BifType::Enum::Input::Event = internal_type("Input::Event")->AsEnumType();
	BifType::Record::Input::TableDescription = internal_type("Input::TableDescription")->AsRecordType();
	BifType::Record::Input::EventDescription = internal_type("Input::EventDescription")->AsRecordType();
	BifType::Record::Input::AnalysisDescription = internal_type("Input::AnalysisDescription")->AsRecordType();
	(void) new BuiltinFunc(BifFunc::Input::bro___create_table_stream, "Input::__create_table_stream", 0);
	(void) new BuiltinFunc(BifFunc::Input::bro___create_event_stream, "Input::__create_event_stream", 0);
	(void) new BuiltinFunc(BifFunc::Input::bro___create_analysis_stream, "Input::__create_analysis_stream", 0);
	(void) new BuiltinFunc(BifFunc::Input::bro___remove_stream, "Input::__remove_stream", 0);
	(void) new BuiltinFunc(BifFunc::Input::bro___force_update, "Input::__force_update", 0);
	BifConst::Input::accept_unsupported_types = internal_const_val("Input::accept_unsupported_types")->AsBool();
