// This file was automatically generated by bifcl from /home/ubuntu/bro/src/input/input.bif (alternative mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_input_input_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_input_input_bif
#define _home_ubuntu_bro_my_build_dir_src_input_input_bif
#include "bro-bif.h"
#endif
#endif

namespace BifEnum { namespace Input { enum Event {
	EVENT_NEW = 0,
	EVENT_CHANGED = 1,
	EVENT_REMOVED = 2,
}; } }
namespace BifType { namespace Enum{ namespace Input {  extern EnumType * Event;  } } }
namespace BifType { namespace Record{ namespace Input {  extern RecordType * TableDescription;  } } }
namespace BifType { namespace Record{ namespace Input {  extern RecordType * EventDescription;  } } }
namespace BifType { namespace Record{ namespace Input {  extern RecordType * AnalysisDescription;  } } }
namespace BifFunc { namespace Input { extern Val* bro___create_table_stream(Frame* frame, val_list*); }  }
namespace BifFunc { namespace Input { extern Val* bro___create_event_stream(Frame* frame, val_list*); }  }
namespace BifFunc { namespace Input { extern Val* bro___create_analysis_stream(Frame* frame, val_list*); }  }
namespace BifFunc { namespace Input { extern Val* bro___remove_stream(Frame* frame, val_list*); }  }
namespace BifFunc { namespace Input { extern Val* bro___force_update(Frame* frame, val_list*); }  }
namespace BifConst { namespace Input {  extern int accept_unsupported_types;  }  }

#endif
