// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/mime/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_MIME {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::mime_begin_entity = internal_handler("mime_begin_entity");
	plugin->AddBifItem("mime_begin_entity", plugin::BifItem::EVENT);
	::mime_end_entity = internal_handler("mime_end_entity");
	plugin->AddBifItem("mime_end_entity", plugin::BifItem::EVENT);
	::mime_one_header = internal_handler("mime_one_header");
	plugin->AddBifItem("mime_one_header", plugin::BifItem::EVENT);
	::mime_all_headers = internal_handler("mime_all_headers");
	plugin->AddBifItem("mime_all_headers", plugin::BifItem::EVENT);
	::mime_segment_data = internal_handler("mime_segment_data");
	plugin->AddBifItem("mime_segment_data", plugin::BifItem::EVENT);
	::mime_entity_data = internal_handler("mime_entity_data");
	plugin->AddBifItem("mime_entity_data", plugin::BifItem::EVENT);
	::mime_all_data = internal_handler("mime_all_data");
	plugin->AddBifItem("mime_all_data", plugin::BifItem::EVENT);
	::mime_event = internal_handler("mime_event");
	plugin->AddBifItem("mime_event", plugin::BifItem::EVENT);
	::mime_content_hash = internal_handler("mime_content_hash");
	plugin->AddBifItem("mime_content_hash", plugin::BifItem::EVENT);

	}
} }


