// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/file/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_File {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_File_events("Bro::File", __bif_events_init);
} }
