// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/file/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_File {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::file_transferred = internal_handler("file_transferred");
	plugin->AddBifItem("file_transferred", plugin::BifItem::EVENT);

	}
} }


