// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/file/events.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_analyzer_protocol_file_events_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_file_events_bif
#define _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_file_events_bif
#include "bro-bif.h"
#endif
#endif

extern EventHandlerPtr file_transferred; 
namespace BifEvent {  void generate_file_transferred(analyzer::Analyzer* analyzer, Connection* c, StringVal* prefix, StringVal* descr, StringVal* mime_type);  } 

#endif
