// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/dce-rpc/events.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_analyzer_protocol_dce_rpc_events_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_dce_rpc_events_bif
#define _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_dce_rpc_events_bif
#include "bro-bif.h"
#endif
#endif

extern EventHandlerPtr dce_rpc_message; 
namespace BifEvent {  void generate_dce_rpc_message(analyzer::Analyzer* analyzer, Connection* c, int is_orig, bro_uint_t fid, bro_uint_t ptype_id, Val* ptype);  } 
extern EventHandlerPtr dce_rpc_bind; 
namespace BifEvent {  void generate_dce_rpc_bind(analyzer::Analyzer* analyzer, Connection* c, bro_uint_t fid, StringVal* uuid, bro_uint_t ver_major, bro_uint_t ver_minor);  } 
extern EventHandlerPtr dce_rpc_bind_ack; 
namespace BifEvent {  void generate_dce_rpc_bind_ack(analyzer::Analyzer* analyzer, Connection* c, bro_uint_t fid, StringVal* sec_addr);  } 
extern EventHandlerPtr dce_rpc_request; 
namespace BifEvent {  void generate_dce_rpc_request(analyzer::Analyzer* analyzer, Connection* c, bro_uint_t fid, bro_uint_t opnum, bro_uint_t stub_len);  } 
extern EventHandlerPtr dce_rpc_response; 
namespace BifEvent {  void generate_dce_rpc_response(analyzer::Analyzer* analyzer, Connection* c, bro_uint_t fid, bro_uint_t opnum, bro_uint_t stub_len);  } 

#endif
