// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/dce-rpc/types.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_DCE_RPC {
void __bif_types_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_DCE_RPC_types("Bro::DCE_RPC", __bif_types_init);
} }
