// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/ntlm/events.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_analyzer_protocol_ntlm_events_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_ntlm_events_bif
#define _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_ntlm_events_bif
#include "bro-bif.h"
#endif
#endif

extern EventHandlerPtr ntlm_negotiate; 
namespace BifEvent {  void generate_ntlm_negotiate(analyzer::Analyzer* analyzer, Connection* c, Val* negotiate);  } 
extern EventHandlerPtr ntlm_challenge; 
namespace BifEvent {  void generate_ntlm_challenge(analyzer::Analyzer* analyzer, Connection* c, Val* challenge);  } 
extern EventHandlerPtr ntlm_authenticate; 
namespace BifEvent {  void generate_ntlm_authenticate(analyzer::Analyzer* analyzer, Connection* c, Val* request);  } 

#endif
