// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/ntlm/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_NTLM {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_NTLM_events("Bro::NTLM", __bif_events_init);
} }
