// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/ntlm/types.bif (plugin mode).


#include "types.bif.h"

namespace BifType { namespace Record{ namespace NTLM {  RecordType * Negotiate;  } } }
namespace BifType { namespace Record{ namespace NTLM {  RecordType * Challenge;  } } }
namespace BifType { namespace Record{ namespace NTLM {  RecordType * Authenticate;  } } }
namespace BifType { namespace Record{ namespace NTLM {  RecordType * NegotiateFlags;  } } }
namespace BifType { namespace Record{ namespace NTLM {  RecordType * Version;  } } }
namespace BifType { namespace Record{ namespace NTLM {  RecordType * AVs;  } } }
