# This file was automatically generated by bifcl from /home/ubuntu/bro/src/broker-dummy/store.bif (alternative mode).


##! Placeholder for Broker-based communication functionality, not enabled
##! by default
export {
} # end of export section
module GLOBAL;
