// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/rfb/events.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_analyzer_protocol_rfb_events_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_rfb_events_bif
#define _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_rfb_events_bif
#include "bro-bif.h"
#endif
#endif

extern EventHandlerPtr rfb_event; 
namespace BifEvent {  void generate_rfb_event(analyzer::Analyzer* analyzer, Connection* c);  } 
extern EventHandlerPtr rfb_authentication_type; 
namespace BifEvent {  void generate_rfb_authentication_type(analyzer::Analyzer* analyzer, Connection* c, bro_uint_t authtype);  } 
extern EventHandlerPtr rfb_auth_result; 
namespace BifEvent {  void generate_rfb_auth_result(analyzer::Analyzer* analyzer, Connection* c, int result);  } 
extern EventHandlerPtr rfb_share_flag; 
namespace BifEvent {  void generate_rfb_share_flag(analyzer::Analyzer* analyzer, Connection* c, int flag);  } 
extern EventHandlerPtr rfb_client_version; 
namespace BifEvent {  void generate_rfb_client_version(analyzer::Analyzer* analyzer, Connection* c, StringVal* major_version, StringVal* minor_version);  } 
extern EventHandlerPtr rfb_server_version; 
namespace BifEvent {  void generate_rfb_server_version(analyzer::Analyzer* analyzer, Connection* c, StringVal* major_version, StringVal* minor_version);  } 
extern EventHandlerPtr rfb_server_parameters; 
namespace BifEvent {  void generate_rfb_server_parameters(analyzer::Analyzer* analyzer, Connection* c, StringVal* name, bro_uint_t width, bro_uint_t height);  } 

#endif
