// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/rfb/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_RFB {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::rfb_event = internal_handler("rfb_event");
	plugin->AddBifItem("rfb_event", plugin::BifItem::EVENT);
	::rfb_authentication_type = internal_handler("rfb_authentication_type");
	plugin->AddBifItem("rfb_authentication_type", plugin::BifItem::EVENT);
	::rfb_auth_result = internal_handler("rfb_auth_result");
	plugin->AddBifItem("rfb_auth_result", plugin::BifItem::EVENT);
	::rfb_share_flag = internal_handler("rfb_share_flag");
	plugin->AddBifItem("rfb_share_flag", plugin::BifItem::EVENT);
	::rfb_client_version = internal_handler("rfb_client_version");
	plugin->AddBifItem("rfb_client_version", plugin::BifItem::EVENT);
	::rfb_server_version = internal_handler("rfb_server_version");
	plugin->AddBifItem("rfb_server_version", plugin::BifItem::EVENT);
	::rfb_server_parameters = internal_handler("rfb_server_parameters");
	plugin->AddBifItem("rfb_server_parameters", plugin::BifItem::EVENT);

	}
} }


