// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/dnp3/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_DNP3 {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_DNP3_events("Bro::DNP3", __bif_events_init);
} }
