// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/login/functions.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_Login {
void __bif_functions_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_Login_functions("Bro::Login", __bif_functions_init);
} }
