// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/login/functions.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "functions.bif.h"

namespace plugin { namespace Bro_Login {

void __bif_functions_init(plugin::Plugin* plugin)
	{
	(void) new BuiltinFunc(BifFunc::bro_get_login_state, "get_login_state", 0);
	plugin->AddBifItem("get_login_state", plugin::BifItem::FUNCTION);
	(void) new BuiltinFunc(BifFunc::bro_set_login_state, "set_login_state", 0);
	plugin->AddBifItem("set_login_state", plugin::BifItem::FUNCTION);

	}
} }


