#!/bin/sh

version=2.5-534
prefix=/usr/local
script_dir=/usr/local/share/bro
site_dir=/usr/local/share/bro/site
plugin_dir=/usr/local/lib/bro/plugins
config_dir=
python_dir=
bropath=.:/usr/local/share/bro:/usr/local/share/bro/policy:/usr/local/share/bro/site
bro_dist=/home/ubuntu/bro

usage="\
Usage: bro-config [--version] [--prefix] [--script_dir] [--site_dir] [--plugin_dir] [--config_dir] [--python_dir] [--bropath] [--bro_dist]"

if [ $# -eq 0 ] ; then
      echo "${usage}" 1>&2
      exit 1
fi

while [ $# -ne 0 ]; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --version)
      echo $version
      ;;
    --prefix)
      echo $prefix
      ;;
    --script_dir)
      echo $script_dir
      ;;
    --site_dir)
      echo $site_dir
      ;;
    --plugin_dir)
      echo $plugin_dir
      ;;
    --config_dir)
      echo $config_dir
      ;;
    --python_dir)
      echo $python_dir
      ;;
    --bropath)
      echo $bropath
      ;;
    --bro_dist)
      echo $bro_dist
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done

exit 0
