// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/gtpv1/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_GTPv1 {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::gtpv1_message = internal_handler("gtpv1_message");
	plugin->AddBifItem("gtpv1_message", plugin::BifItem::EVENT);
	::gtpv1_g_pdu_packet = internal_handler("gtpv1_g_pdu_packet");
	plugin->AddBifItem("gtpv1_g_pdu_packet", plugin::BifItem::EVENT);
	::gtpv1_create_pdp_ctx_request = internal_handler("gtpv1_create_pdp_ctx_request");
	plugin->AddBifItem("gtpv1_create_pdp_ctx_request", plugin::BifItem::EVENT);
	::gtpv1_create_pdp_ctx_response = internal_handler("gtpv1_create_pdp_ctx_response");
	plugin->AddBifItem("gtpv1_create_pdp_ctx_response", plugin::BifItem::EVENT);
	::gtpv1_update_pdp_ctx_request = internal_handler("gtpv1_update_pdp_ctx_request");
	plugin->AddBifItem("gtpv1_update_pdp_ctx_request", plugin::BifItem::EVENT);
	::gtpv1_update_pdp_ctx_response = internal_handler("gtpv1_update_pdp_ctx_response");
	plugin->AddBifItem("gtpv1_update_pdp_ctx_response", plugin::BifItem::EVENT);
	::gtpv1_delete_pdp_ctx_request = internal_handler("gtpv1_delete_pdp_ctx_request");
	plugin->AddBifItem("gtpv1_delete_pdp_ctx_request", plugin::BifItem::EVENT);
	::gtpv1_delete_pdp_ctx_response = internal_handler("gtpv1_delete_pdp_ctx_response");
	plugin->AddBifItem("gtpv1_delete_pdp_ctx_response", plugin::BifItem::EVENT);

	}
} }


