// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/rdp/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_RDP {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::rdp_connect_request = internal_handler("rdp_connect_request");
	plugin->AddBifItem("rdp_connect_request", plugin::BifItem::EVENT);
	::rdp_negotiation_response = internal_handler("rdp_negotiation_response");
	plugin->AddBifItem("rdp_negotiation_response", plugin::BifItem::EVENT);
	::rdp_negotiation_failure = internal_handler("rdp_negotiation_failure");
	plugin->AddBifItem("rdp_negotiation_failure", plugin::BifItem::EVENT);
	::rdp_client_core_data = internal_handler("rdp_client_core_data");
	plugin->AddBifItem("rdp_client_core_data", plugin::BifItem::EVENT);
	::rdp_gcc_server_create_response = internal_handler("rdp_gcc_server_create_response");
	plugin->AddBifItem("rdp_gcc_server_create_response", plugin::BifItem::EVENT);
	::rdp_server_security = internal_handler("rdp_server_security");
	plugin->AddBifItem("rdp_server_security", plugin::BifItem::EVENT);
	::rdp_server_certificate = internal_handler("rdp_server_certificate");
	plugin->AddBifItem("rdp_server_certificate", plugin::BifItem::EVENT);
	::rdp_begin_encryption = internal_handler("rdp_begin_encryption");
	plugin->AddBifItem("rdp_begin_encryption", plugin::BifItem::EVENT);

	}
} }


