// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/rdp/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_RDP {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_RDP_events("Bro::RDP", __bif_events_init);
} }
