// This file was automatically generated by bifcl from /home/ubuntu/bro/src/probabilistic/bloom-filter.bif (alternative mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_probabilistic_bloom_filter_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_probabilistic_bloom_filter_bif
#define _home_ubuntu_bro_my_build_dir_src_probabilistic_bloom_filter_bif
#include "bro-bif.h"
#endif
#endif

namespace BifFunc { extern Val* bro_bloomfilter_basic_init(Frame* frame, val_list*); } 
namespace BifFunc { extern Val* bro_bloomfilter_basic_init2(Frame* frame, val_list*); } 
namespace BifFunc { extern Val* bro_bloomfilter_counting_init(Frame* frame, val_list*); } 
namespace BifFunc { extern Val* bro_bloomfilter_add(Frame* frame, val_list*); } 
namespace BifFunc { extern Val* bro_bloomfilter_lookup(Frame* frame, val_list*); } 
namespace BifFunc { extern Val* bro_bloomfilter_clear(Frame* frame, val_list*); } 
namespace BifFunc { extern Val* bro_bloomfilter_merge(Frame* frame, val_list*); } 
namespace BifFunc { extern Val* bro_bloomfilter_internal_state(Frame* frame, val_list*); } 

#endif
