// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/imap/events.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_analyzer_protocol_imap_events_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_imap_events_bif
#define _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_imap_events_bif
#include "bro-bif.h"
#endif
#endif

extern EventHandlerPtr imap_capabilities; 
namespace BifEvent {  void generate_imap_capabilities(analyzer::Analyzer* analyzer, Connection* c, Val* capabilities);  } 
extern EventHandlerPtr imap_starttls; 
namespace BifEvent {  void generate_imap_starttls(analyzer::Analyzer* analyzer, Connection* c);  } 

#endif
