// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/modbus/events.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_Modbus {
void __bif_events_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_Modbus_events("Bro::Modbus", __bif_events_init);
} }
