// This file was automatically generated by bifcl from /home/ubuntu/bro/src/broker-dummy/store.bif (alternative mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_broker_dummy_store_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_broker_dummy_store_bif
#define _home_ubuntu_bro_my_build_dir_src_broker_dummy_store_bif
#include "bro-bif.h"
#endif
#endif


#endif
