// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/consts.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "consts.bif.h"

namespace plugin { namespace Bro_SMB {

void __bif_consts_init(plugin::Plugin* plugin)
	{
	BifConst::SMB::pipe_filenames = internal_const_val("SMB::pipe_filenames");
	plugin->AddBifItem("SMB::pipe_filenames", plugin::BifItem::CONSTANT);

	}
} }


