// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/consts.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_analyzer_protocol_smb_consts_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_smb_consts_bif
#define _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_smb_consts_bif
#include "bro-bif.h"
#endif
#endif

namespace BifConst { namespace SMB {  extern Val* pipe_filenames;  }  }

#endif
