// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb1_com_tree_disconnect.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_SMB {
void __bif_smb1_com_tree_disconnect_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_SMB_smb1_com_tree_disconnect("Bro::SMB", __bif_smb1_com_tree_disconnect_init);
} }
