// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb1_com_check_directory.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "smb1_com_check_directory.bif.h"

namespace plugin { namespace Bro_SMB {

void __bif_smb1_com_check_directory_init(plugin::Plugin* plugin)
	{
	::smb1_check_directory_request = internal_handler("smb1_check_directory_request");
	plugin->AddBifItem("smb1_check_directory_request", plugin::BifItem::EVENT);
	::smb1_check_directory_response = internal_handler("smb1_check_directory_response");
	plugin->AddBifItem("smb1_check_directory_response", plugin::BifItem::EVENT);

	}
} }


