// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb1_com_read_andx.bif (plugin mode).


#include "smb1_com_read_andx.bif.h"

EventHandlerPtr smb1_read_andx_request; 
void BifEvent::generate_smb1_read_andx_request(analyzer::Analyzer* analyzer, Connection* c, Val* hdr, bro_uint_t file_id, bro_uint_t offset, bro_uint_t length)
	{
	// Note that it is intentional that here we do not
	// check if ::smb1_read_andx_request is NULL, which should happen *before*
	// BifEvent::generate_smb1_read_andx_request is called to avoid unnecessary Val
	// allocation.

	val_list* vl = new val_list;

	vl->append(c->BuildConnVal());
	vl->append(hdr);
	vl->append(new Val(file_id, TYPE_COUNT));
	vl->append(new Val(offset, TYPE_COUNT));
	vl->append(new Val(length, TYPE_COUNT));

	mgr.QueueEvent(::smb1_read_andx_request, vl, SOURCE_LOCAL, analyzer->GetID(), timer_mgr, c);
	} // event generation
EventHandlerPtr smb1_read_andx_response; 
void BifEvent::generate_smb1_read_andx_response(analyzer::Analyzer* analyzer, Connection* c, Val* hdr, bro_uint_t data_len)
	{
	// Note that it is intentional that here we do not
	// check if ::smb1_read_andx_response is NULL, which should happen *before*
	// BifEvent::generate_smb1_read_andx_response is called to avoid unnecessary Val
	// allocation.

	val_list* vl = new val_list;

	vl->append(c->BuildConnVal());
	vl->append(hdr);
	vl->append(new Val(data_len, TYPE_COUNT));

	mgr.QueueEvent(::smb1_read_andx_response, vl, SOURCE_LOCAL, analyzer->GetID(), timer_mgr, c);
	} // event generation
