// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb1_events.bif (plugin mode).


#include "smb1_events.bif.h"

EventHandlerPtr smb1_message; 
void BifEvent::generate_smb1_message(analyzer::Analyzer* analyzer, Connection* c, Val* hdr, int is_orig)
	{
	// Note that it is intentional that here we do not
	// check if ::smb1_message is NULL, which should happen *before*
	// BifEvent::generate_smb1_message is called to avoid unnecessary Val
	// allocation.

	val_list* vl = new val_list;

	vl->append(c->BuildConnVal());
	vl->append(hdr);
	vl->append(new Val(is_orig, TYPE_BOOL));

	mgr.QueueEvent(::smb1_message, vl, SOURCE_LOCAL, analyzer->GetID(), timer_mgr, c);
	} // event generation
EventHandlerPtr smb1_empty_response; 
void BifEvent::generate_smb1_empty_response(analyzer::Analyzer* analyzer, Connection* c, Val* hdr)
	{
	// Note that it is intentional that here we do not
	// check if ::smb1_empty_response is NULL, which should happen *before*
	// BifEvent::generate_smb1_empty_response is called to avoid unnecessary Val
	// allocation.

	val_list* vl = new val_list;

	vl->append(c->BuildConnVal());
	vl->append(hdr);

	mgr.QueueEvent(::smb1_empty_response, vl, SOURCE_LOCAL, analyzer->GetID(), timer_mgr, c);
	} // event generation
EventHandlerPtr smb1_error; 
void BifEvent::generate_smb1_error(analyzer::Analyzer* analyzer, Connection* c, Val* hdr, int is_orig)
	{
	// Note that it is intentional that here we do not
	// check if ::smb1_error is NULL, which should happen *before*
	// BifEvent::generate_smb1_error is called to avoid unnecessary Val
	// allocation.

	val_list* vl = new val_list;

	vl->append(c->BuildConnVal());
	vl->append(hdr);
	vl->append(new Val(is_orig, TYPE_BOOL));

	mgr.QueueEvent(::smb1_error, vl, SOURCE_LOCAL, analyzer->GetID(), timer_mgr, c);
	} // event generation
