// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb1_com_echo.bif (plugin mode).


#include "smb1_com_echo.bif.h"

EventHandlerPtr smb1_echo_request; 
void BifEvent::generate_smb1_echo_request(analyzer::Analyzer* analyzer, Connection* c, bro_uint_t echo_count, StringVal* data)
	{
	// Note that it is intentional that here we do not
	// check if ::smb1_echo_request is NULL, which should happen *before*
	// BifEvent::generate_smb1_echo_request is called to avoid unnecessary Val
	// allocation.

	val_list* vl = new val_list;

	vl->append(c->BuildConnVal());
	vl->append(new Val(echo_count, TYPE_COUNT));
	vl->append(data);

	mgr.QueueEvent(::smb1_echo_request, vl, SOURCE_LOCAL, analyzer->GetID(), timer_mgr, c);
	} // event generation
EventHandlerPtr smb1_echo_response; 
void BifEvent::generate_smb1_echo_response(analyzer::Analyzer* analyzer, Connection* c, bro_uint_t seq_num, StringVal* data)
	{
	// Note that it is intentional that here we do not
	// check if ::smb1_echo_response is NULL, which should happen *before*
	// BifEvent::generate_smb1_echo_response is called to avoid unnecessary Val
	// allocation.

	val_list* vl = new val_list;

	vl->append(c->BuildConnVal());
	vl->append(new Val(seq_num, TYPE_COUNT));
	vl->append(data);

	mgr.QueueEvent(::smb1_echo_response, vl, SOURCE_LOCAL, analyzer->GetID(), timer_mgr, c);
	} // event generation
