// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb1_com_tree_connect_andx.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "smb1_com_tree_connect_andx.bif.h"

namespace plugin { namespace Bro_SMB {

void __bif_smb1_com_tree_connect_andx_init(plugin::Plugin* plugin)
	{
	::smb1_tree_connect_andx_request = internal_handler("smb1_tree_connect_andx_request");
	plugin->AddBifItem("smb1_tree_connect_andx_request", plugin::BifItem::EVENT);
	::smb1_tree_connect_andx_response = internal_handler("smb1_tree_connect_andx_response");
	plugin->AddBifItem("smb1_tree_connect_andx_response", plugin::BifItem::EVENT);

	}
} }


