// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb1_com_close.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "smb1_com_close.bif.h"

namespace plugin { namespace Bro_SMB {

void __bif_smb1_com_close_init(plugin::Plugin* plugin)
	{
	::smb1_close_request = internal_handler("smb1_close_request");
	plugin->AddBifItem("smb1_close_request", plugin::BifItem::EVENT);

	}
} }


