// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb1_com_check_directory.bif (plugin mode).


#include "smb1_com_check_directory.bif.h"

EventHandlerPtr smb1_check_directory_request; 
void BifEvent::generate_smb1_check_directory_request(analyzer::Analyzer* analyzer, Connection* c, Val* hdr, StringVal* directory_name)
	{
	// Note that it is intentional that here we do not
	// check if ::smb1_check_directory_request is NULL, which should happen *before*
	// BifEvent::generate_smb1_check_directory_request is called to avoid unnecessary Val
	// allocation.

	val_list* vl = new val_list;

	vl->append(c->BuildConnVal());
	vl->append(hdr);
	vl->append(directory_name);

	mgr.QueueEvent(::smb1_check_directory_request, vl, SOURCE_LOCAL, analyzer->GetID(), timer_mgr, c);
	} // event generation
EventHandlerPtr smb1_check_directory_response; 
void BifEvent::generate_smb1_check_directory_response(analyzer::Analyzer* analyzer, Connection* c, Val* hdr)
	{
	// Note that it is intentional that here we do not
	// check if ::smb1_check_directory_response is NULL, which should happen *before*
	// BifEvent::generate_smb1_check_directory_response is called to avoid unnecessary Val
	// allocation.

	val_list* vl = new val_list;

	vl->append(c->BuildConnVal());
	vl->append(hdr);

	mgr.QueueEvent(::smb1_check_directory_response, vl, SOURCE_LOCAL, analyzer->GetID(), timer_mgr, c);
	} // event generation
