// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb1_com_echo.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_analyzer_protocol_smb_smb1_com_echo_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_smb_smb1_com_echo_bif
#define _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_smb_smb1_com_echo_bif
#include "bro-bif.h"
#endif
#endif

extern EventHandlerPtr smb1_echo_request; 
namespace BifEvent {  void generate_smb1_echo_request(analyzer::Analyzer* analyzer, Connection* c, bro_uint_t echo_count, StringVal* data);  } 
extern EventHandlerPtr smb1_echo_response; 
namespace BifEvent {  void generate_smb1_echo_response(analyzer::Analyzer* analyzer, Connection* c, bro_uint_t seq_num, StringVal* data);  } 

#endif
