// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb1_com_create_directory.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_analyzer_protocol_smb_smb1_com_create_directory_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_smb_smb1_com_create_directory_bif
#define _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_smb_smb1_com_create_directory_bif
#include "bro-bif.h"
#endif
#endif

extern EventHandlerPtr smb1_create_directory_request; 
namespace BifEvent {  void generate_smb1_create_directory_request(analyzer::Analyzer* analyzer, Connection* c, Val* hdr, StringVal* directory_name);  } 
extern EventHandlerPtr smb1_create_directory_response; 
namespace BifEvent {  void generate_smb1_create_directory_response(analyzer::Analyzer* analyzer, Connection* c, Val* hdr);  } 

#endif
