// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb1_com_transaction2.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_analyzer_protocol_smb_smb1_com_transaction2_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_smb_smb1_com_transaction2_bif
#define _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_smb_smb1_com_transaction2_bif
#include "bro-bif.h"
#endif
#endif

extern EventHandlerPtr smb1_transaction2_request; 
namespace BifEvent {  void generate_smb1_transaction2_request(analyzer::Analyzer* analyzer, Connection* c, Val* hdr, Val* args, bro_uint_t sub_cmd);  } 
extern EventHandlerPtr smb1_trans2_find_first2_request; 
namespace BifEvent {  void generate_smb1_trans2_find_first2_request(analyzer::Analyzer* analyzer, Connection* c, Val* hdr, Val* args);  } 
extern EventHandlerPtr smb1_trans2_query_path_info_request; 
namespace BifEvent {  void generate_smb1_trans2_query_path_info_request(analyzer::Analyzer* analyzer, Connection* c, Val* hdr, StringVal* file_name);  } 
extern EventHandlerPtr smb1_trans2_get_dfs_referral_request; 
namespace BifEvent {  void generate_smb1_trans2_get_dfs_referral_request(analyzer::Analyzer* analyzer, Connection* c, Val* hdr, StringVal* file_name);  } 
namespace BifType { namespace Record{ namespace SMB1 {  extern RecordType * Find_First2_Request_Args;  } } }
namespace BifType { namespace Record{ namespace SMB1 {  extern RecordType * Find_First2_Response_Args;  } } }
namespace BifType { namespace Record{ namespace SMB1 {  extern RecordType * Trans2_Args;  } } }

#endif
