// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb1_com_query_information.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "smb1_com_query_information.bif.h"

namespace plugin { namespace Bro_SMB {

void __bif_smb1_com_query_information_init(plugin::Plugin* plugin)
	{
	::smb1_query_information_request = internal_handler("smb1_query_information_request");
	plugin->AddBifItem("smb1_query_information_request", plugin::BifItem::EVENT);

	}
} }


