// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb1_com_logoff_andx.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "smb1_com_logoff_andx.bif.h"

namespace plugin { namespace Bro_SMB {

void __bif_smb1_com_logoff_andx_init(plugin::Plugin* plugin)
	{
	::smb1_logoff_andx = internal_handler("smb1_logoff_andx");
	plugin->AddBifItem("smb1_logoff_andx", plugin::BifItem::EVENT);

	}
} }


