// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb1_events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "smb1_events.bif.h"

namespace plugin { namespace Bro_SMB {

void __bif_smb1_events_init(plugin::Plugin* plugin)
	{
	::smb1_message = internal_handler("smb1_message");
	plugin->AddBifItem("smb1_message", plugin::BifItem::EVENT);
	::smb1_empty_response = internal_handler("smb1_empty_response");
	plugin->AddBifItem("smb1_empty_response", plugin::BifItem::EVENT);
	::smb1_error = internal_handler("smb1_error");
	plugin->AddBifItem("smb1_error", plugin::BifItem::EVENT);

	}
} }


