// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb1_com_transaction.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "smb1_com_transaction.bif.h"

namespace plugin { namespace Bro_SMB {

void __bif_smb1_com_transaction_init(plugin::Plugin* plugin)
	{
	::smb1_transaction_request = internal_handler("smb1_transaction_request");
	plugin->AddBifItem("smb1_transaction_request", plugin::BifItem::EVENT);
	::smb1_transaction_response = internal_handler("smb1_transaction_response");
	plugin->AddBifItem("smb1_transaction_response", plugin::BifItem::EVENT);

	}
} }


