// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb2_events.bif (plugin mode).


#include "smb2_events.bif.h"

EventHandlerPtr smb2_message; 
void BifEvent::generate_smb2_message(analyzer::Analyzer* analyzer, Connection* c, Val* hdr, int is_orig)
	{
	// Note that it is intentional that here we do not
	// check if ::smb2_message is NULL, which should happen *before*
	// BifEvent::generate_smb2_message is called to avoid unnecessary Val
	// allocation.

	val_list* vl = new val_list;

	vl->append(c->BuildConnVal());
	vl->append(hdr);
	vl->append(new Val(is_orig, TYPE_BOOL));

	mgr.QueueEvent(::smb2_message, vl, SOURCE_LOCAL, analyzer->GetID(), timer_mgr, c);
	} // event generation
