// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb2_com_set_info.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "smb2_com_set_info.bif.h"

namespace plugin { namespace Bro_SMB {

void __bif_smb2_com_set_info_init(plugin::Plugin* plugin)
	{
	::smb2_file_rename = internal_handler("smb2_file_rename");
	plugin->AddBifItem("smb2_file_rename", plugin::BifItem::EVENT);
	::smb2_file_delete = internal_handler("smb2_file_delete");
	plugin->AddBifItem("smb2_file_delete", plugin::BifItem::EVENT);

	}
} }


