// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb2_com_tree_disconnect.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "smb2_com_tree_disconnect.bif.h"

namespace plugin { namespace Bro_SMB {

void __bif_smb2_com_tree_disconnect_init(plugin::Plugin* plugin)
	{
	::smb2_tree_disconnect_request = internal_handler("smb2_tree_disconnect_request");
	plugin->AddBifItem("smb2_tree_disconnect_request", plugin::BifItem::EVENT);
	::smb2_tree_disconnect_response = internal_handler("smb2_tree_disconnect_response");
	plugin->AddBifItem("smb2_tree_disconnect_response", plugin::BifItem::EVENT);

	}
} }


