// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb2_com_tree_connect.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "smb2_com_tree_connect.bif.h"

namespace plugin { namespace Bro_SMB {

void __bif_smb2_com_tree_connect_init(plugin::Plugin* plugin)
	{
	::smb2_tree_connect_request = internal_handler("smb2_tree_connect_request");
	plugin->AddBifItem("smb2_tree_connect_request", plugin::BifItem::EVENT);
	::smb2_tree_connect_response = internal_handler("smb2_tree_connect_response");
	plugin->AddBifItem("smb2_tree_connect_response", plugin::BifItem::EVENT);
	BifType::Record::SMB2::TreeConnectResponse = internal_type("SMB2::TreeConnectResponse")->AsRecordType();
	plugin->AddBifItem("SMB2::TreeConnectResponse", plugin::BifItem::TYPE);

	}
} }


