// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb2_com_set_info.bif (plugin mode).


#include "smb2_com_set_info.bif.h"

EventHandlerPtr smb2_file_rename; 
void BifEvent::generate_smb2_file_rename(analyzer::Analyzer* analyzer, Connection* c, Val* hdr, Val* file_id, StringVal* dst_filename)
	{
	// Note that it is intentional that here we do not
	// check if ::smb2_file_rename is NULL, which should happen *before*
	// BifEvent::generate_smb2_file_rename is called to avoid unnecessary Val
	// allocation.

	val_list* vl = new val_list;

	vl->append(c->BuildConnVal());
	vl->append(hdr);
	vl->append(file_id);
	vl->append(dst_filename);

	mgr.QueueEvent(::smb2_file_rename, vl, SOURCE_LOCAL, analyzer->GetID(), timer_mgr, c);
	} // event generation
EventHandlerPtr smb2_file_delete; 
void BifEvent::generate_smb2_file_delete(analyzer::Analyzer* analyzer, Connection* c, Val* hdr, Val* file_id, int delete_pending)
	{
	// Note that it is intentional that here we do not
	// check if ::smb2_file_delete is NULL, which should happen *before*
	// BifEvent::generate_smb2_file_delete is called to avoid unnecessary Val
	// allocation.

	val_list* vl = new val_list;

	vl->append(c->BuildConnVal());
	vl->append(hdr);
	vl->append(file_id);
	vl->append(new Val(delete_pending, TYPE_BOOL));

	mgr.QueueEvent(::smb2_file_delete, vl, SOURCE_LOCAL, analyzer->GetID(), timer_mgr, c);
	} // event generation
