// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb2_com_tree_disconnect.bif (plugin mode).


#include "smb2_com_tree_disconnect.bif.h"

EventHandlerPtr smb2_tree_disconnect_request; 
void BifEvent::generate_smb2_tree_disconnect_request(analyzer::Analyzer* analyzer, Connection* c, Val* hdr)
	{
	// Note that it is intentional that here we do not
	// check if ::smb2_tree_disconnect_request is NULL, which should happen *before*
	// BifEvent::generate_smb2_tree_disconnect_request is called to avoid unnecessary Val
	// allocation.

	val_list* vl = new val_list;

	vl->append(c->BuildConnVal());
	vl->append(hdr);

	mgr.QueueEvent(::smb2_tree_disconnect_request, vl, SOURCE_LOCAL, analyzer->GetID(), timer_mgr, c);
	} // event generation
EventHandlerPtr smb2_tree_disconnect_response; 
void BifEvent::generate_smb2_tree_disconnect_response(analyzer::Analyzer* analyzer, Connection* c, Val* hdr)
	{
	// Note that it is intentional that here we do not
	// check if ::smb2_tree_disconnect_response is NULL, which should happen *before*
	// BifEvent::generate_smb2_tree_disconnect_response is called to avoid unnecessary Val
	// allocation.

	val_list* vl = new val_list;

	vl->append(c->BuildConnVal());
	vl->append(hdr);

	mgr.QueueEvent(::smb2_tree_disconnect_response, vl, SOURCE_LOCAL, analyzer->GetID(), timer_mgr, c);
	} // event generation
