// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb2_com_create.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_SMB {
void __bif_smb2_com_create_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_SMB_smb2_com_create("Bro::SMB", __bif_smb2_com_create_init);
} }
