// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb2_events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "smb2_events.bif.h"

namespace plugin { namespace Bro_SMB {

void __bif_smb2_events_init(plugin::Plugin* plugin)
	{
	::smb2_message = internal_handler("smb2_message");
	plugin->AddBifItem("smb2_message", plugin::BifItem::EVENT);

	}
} }


