// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb2_com_create.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_analyzer_protocol_smb_smb2_com_create_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_smb_smb2_com_create_bif
#define _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_smb_smb2_com_create_bif
#include "bro-bif.h"
#endif
#endif

extern EventHandlerPtr smb2_create_request; 
namespace BifEvent {  void generate_smb2_create_request(analyzer::Analyzer* analyzer, Connection* c, Val* hdr, Val* request);  } 
extern EventHandlerPtr smb2_create_response; 
namespace BifEvent {  void generate_smb2_create_response(analyzer::Analyzer* analyzer, Connection* c, Val* hdr, Val* response);  } 
namespace BifType { namespace Record{ namespace SMB2 {  extern RecordType * CreateRequest;  } } }
namespace BifType { namespace Record{ namespace SMB2 {  extern RecordType * CreateResponse;  } } }

#endif
