// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smb/smb2_com_write.bif (plugin mode).


#include "smb2_com_write.bif.h"

EventHandlerPtr smb2_write_request; 
void BifEvent::generate_smb2_write_request(analyzer::Analyzer* analyzer, Connection* c, Val* hdr, Val* file_id, bro_uint_t offset, bro_uint_t length)
	{
	// Note that it is intentional that here we do not
	// check if ::smb2_write_request is NULL, which should happen *before*
	// BifEvent::generate_smb2_write_request is called to avoid unnecessary Val
	// allocation.

	val_list* vl = new val_list;

	vl->append(c->BuildConnVal());
	vl->append(hdr);
	vl->append(file_id);
	vl->append(new Val(offset, TYPE_COUNT));
	vl->append(new Val(length, TYPE_COUNT));

	mgr.QueueEvent(::smb2_write_request, vl, SOURCE_LOCAL, analyzer->GetID(), timer_mgr, c);
	} // event generation
