// This file was automatically generated by bifcl from /home/ubuntu/bro/src/iosource/pcap/pcap.bif (alternative mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_iosource_pcap_pcap_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_iosource_pcap_pcap_bif
#define _home_ubuntu_bro_my_build_dir_src_iosource_pcap_pcap_bif
#include "bro-bif.h"
#endif
#endif

namespace BifConst { namespace Pcap {  extern bro_uint_t snaplen;  }  }
namespace BifConst { namespace Pcap {  extern bro_uint_t bufsize;  }  }
namespace BifFunc { namespace Pcap { extern Val* bro_precompile_pcap_filter(Frame* frame, val_list*); }  }
namespace BifFunc { namespace Pcap { extern Val* bro_install_pcap_filter(Frame* frame, val_list*); }  }
namespace BifFunc { namespace Pcap { extern Val* bro_error(Frame* frame, val_list*); }  }

#endif
