// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/interconn/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_InterConn {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::interconn_stats = internal_handler("interconn_stats");
	plugin->AddBifItem("interconn_stats", plugin::BifItem::EVENT);
	::interconn_remove_conn = internal_handler("interconn_remove_conn");
	plugin->AddBifItem("interconn_remove_conn", plugin::BifItem::EVENT);

	}
} }


