// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/finger/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_Finger {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::finger_request = internal_handler("finger_request");
	plugin->AddBifItem("finger_request", plugin::BifItem::EVENT);
	::finger_reply = internal_handler("finger_reply");
	plugin->AddBifItem("finger_reply", plugin::BifItem::EVENT);

	}
} }


