// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/finger/events.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_analyzer_protocol_finger_events_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_finger_events_bif
#define _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_finger_events_bif
#include "bro-bif.h"
#endif
#endif

extern EventHandlerPtr finger_request; 
namespace BifEvent {  void generate_finger_request(analyzer::Analyzer* analyzer, Connection* c, int full, StringVal* username, StringVal* hostname);  } 
extern EventHandlerPtr finger_reply; 
namespace BifEvent {  void generate_finger_reply(analyzer::Analyzer* analyzer, Connection* c, StringVal* reply_line);  } 

#endif
