// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/sip/events.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_analyzer_protocol_sip_events_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_sip_events_bif
#define _home_ubuntu_bro_my_build_dir_src_analyzer_protocol_sip_events_bif
#include "bro-bif.h"
#endif
#endif

extern EventHandlerPtr sip_request; 
namespace BifEvent {  void generate_sip_request(analyzer::Analyzer* analyzer, Connection* c, StringVal* method, StringVal* original_URI, StringVal* version);  } 
extern EventHandlerPtr sip_reply; 
namespace BifEvent {  void generate_sip_reply(analyzer::Analyzer* analyzer, Connection* c, StringVal* version, bro_uint_t code, StringVal* reason);  } 
extern EventHandlerPtr sip_header; 
namespace BifEvent {  void generate_sip_header(analyzer::Analyzer* analyzer, Connection* c, int is_orig, StringVal* name, StringVal* value);  } 
extern EventHandlerPtr sip_all_headers; 
namespace BifEvent {  void generate_sip_all_headers(analyzer::Analyzer* analyzer, Connection* c, int is_orig, Val* hlist);  } 
extern EventHandlerPtr sip_begin_entity; 
namespace BifEvent {  void generate_sip_begin_entity(analyzer::Analyzer* analyzer, Connection* c, int is_orig);  } 
extern EventHandlerPtr sip_end_entity; 
namespace BifEvent {  void generate_sip_end_entity(analyzer::Analyzer* analyzer, Connection* c, int is_orig);  } 

#endif
