// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/sip/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_SIP {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::sip_request = internal_handler("sip_request");
	plugin->AddBifItem("sip_request", plugin::BifItem::EVENT);
	::sip_reply = internal_handler("sip_reply");
	plugin->AddBifItem("sip_reply", plugin::BifItem::EVENT);
	::sip_header = internal_handler("sip_header");
	plugin->AddBifItem("sip_header", plugin::BifItem::EVENT);
	::sip_all_headers = internal_handler("sip_all_headers");
	plugin->AddBifItem("sip_all_headers", plugin::BifItem::EVENT);
	::sip_begin_entity = internal_handler("sip_begin_entity");
	plugin->AddBifItem("sip_begin_entity", plugin::BifItem::EVENT);
	::sip_end_entity = internal_handler("sip_end_entity");
	plugin->AddBifItem("sip_end_entity", plugin::BifItem::EVENT);

	}
} }


