// This file was automatically generated by bifcl from /home/ubuntu/bro/src/file_analysis/analyzer/pe/events.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_file_analysis_analyzer_pe_events_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_file_analysis_analyzer_pe_events_bif
#define _home_ubuntu_bro_my_build_dir_src_file_analysis_analyzer_pe_events_bif
#include "bro-bif.h"
#endif
#endif

extern EventHandlerPtr pe_dos_header; 
namespace BifEvent {  void generate_pe_dos_header(analyzer::Analyzer* analyzer, Val* f, Val* h);  } 
extern EventHandlerPtr pe_dos_code; 
namespace BifEvent {  void generate_pe_dos_code(analyzer::Analyzer* analyzer, Val* f, StringVal* code);  } 
extern EventHandlerPtr pe_file_header; 
namespace BifEvent {  void generate_pe_file_header(analyzer::Analyzer* analyzer, Val* f, Val* h);  } 
extern EventHandlerPtr pe_optional_header; 
namespace BifEvent {  void generate_pe_optional_header(analyzer::Analyzer* analyzer, Val* f, Val* h);  } 
extern EventHandlerPtr pe_section_header; 
namespace BifEvent {  void generate_pe_section_header(analyzer::Analyzer* analyzer, Val* f, Val* h);  } 

#endif
