// This file was automatically generated by bifcl from /home/ubuntu/bro/src/file_analysis/analyzer/pe/events.bif (plugin mode).


#include <list>
#include <string>
#include "plugin/Plugin.h"
#include "events.bif.h"

namespace plugin { namespace Bro_PE {

void __bif_events_init(plugin::Plugin* plugin)
	{
	::pe_dos_header = internal_handler("pe_dos_header");
	plugin->AddBifItem("pe_dos_header", plugin::BifItem::EVENT);
	::pe_dos_code = internal_handler("pe_dos_code");
	plugin->AddBifItem("pe_dos_code", plugin::BifItem::EVENT);
	::pe_file_header = internal_handler("pe_file_header");
	plugin->AddBifItem("pe_file_header", plugin::BifItem::EVENT);
	::pe_optional_header = internal_handler("pe_optional_header");
	plugin->AddBifItem("pe_optional_header", plugin::BifItem::EVENT);
	::pe_section_header = internal_handler("pe_section_header");
	plugin->AddBifItem("pe_section_header", plugin::BifItem::EVENT);

	}
} }


