// This file was automatically generated by bifcl from /home/ubuntu/bro/src/logging/writers/none/none.bif (plugin mode).


#include "none.bif.h"

namespace BifConst { namespace LogNone {  int debug;  }  }
