// This file was automatically generated by bifcl from /home/ubuntu/bro/src/logging/writers/none/none.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_NoneWriter {
void __bif_none_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_NoneWriter_none("Bro::NoneWriter", __bif_none_init);
} }
