// This file was automatically generated by bifcl from /home/ubuntu/bro/src/analyzer/protocol/smtp/functions.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_SMTP {
void __bif_functions_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_SMTP_functions("Bro::SMTP", __bif_functions_init);
} }
