// This file was automatically generated by bifcl from /home/ubuntu/bro/src/logging/writers/sqlite/sqlite.bif (plugin mode).

#if defined(BRO_IN_NETVAR) || ! defined(_home_ubuntu_bro_my_build_dir_src_logging_writers_sqlite_sqlite_bif)
#ifndef BRO_IN_NETVAR
#ifndef _home_ubuntu_bro_my_build_dir_src_logging_writers_sqlite_sqlite_bif
#define _home_ubuntu_bro_my_build_dir_src_logging_writers_sqlite_sqlite_bif
#include "bro-bif.h"
#endif
#endif

namespace BifConst { namespace LogSQLite {  extern StringVal* set_separator;  }  }
namespace BifConst { namespace LogSQLite {  extern StringVal* empty_field;  }  }
namespace BifConst { namespace LogSQLite {  extern StringVal* unset_field;  }  }

#endif
