// This file was automatically generated by bifcl from /home/ubuntu/bro/src/logging/writers/sqlite/sqlite.bif (plugin mode).

#include "plugin/Manager.h"

namespace plugin { namespace Bro_SQLiteWriter {
void __bif_sqlite_init(plugin::Plugin* plugin);
::plugin::__RegisterBif __register_bifs_Bro_SQLiteWriter_sqlite("Bro::SQLiteWriter", __bif_sqlite_init);
} }
